### ISSUE TITLE
Redeem Restart Link

### ISSUE THREAD

**Issue by OCD3DP** [goeland86/Umikaze2#35]
The Redeem Reset link within the System drop down is missing.

Thanks!

**Comment by GearheadRed** [comment]
Which version of Kamikaze/Umikaze are you running?

**Comment by OCD3DP** [comment]
Kamikaze-2.1.1rc1 in my delta...
Kamikaze-2.1.0b in the cartesian...

**Comment by goeland86** [comment]
Will be fixed in the next RC. Re-open if problems persist.
